package com.example.seachem_dosing.ui.theme

import androidx.compose.ui.graphics.Color

// Mirrors res/values/colors.xml (md_theme_*). Keep in sync if the XML palette changes.

// --- Light ---
val LightPrimary = Color(0xFF0A7A8C)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFB9F1F5)
val LightOnPrimaryContainer = Color(0xFF00363D)
val LightSecondary = Color(0xFF4F6269)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFD2E7EE)
val LightOnSecondaryContainer = Color(0xFF0B1F25)
val LightTertiary = Color(0xFFC86C2D)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFFFDCC7)
val LightOnTertiaryContainer = Color(0xFF3A1200)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFF6FAFB)
val LightOnBackground = Color(0xFF0F1416)
val LightSurface = Color(0xFFF6FAFB)
val LightOnSurface = Color(0xFF0F1416)
val LightSurfaceVariant = Color(0xFFD7E4E9)
val LightOnSurfaceVariant = Color(0xFF3D494E)
val LightOutline = Color(0xFF6E7B82)
val LightOutlineVariant = Color(0xFFBECAD0)
val LightInverseSurface = Color(0xFF253035)
val LightInverseOnSurface = Color(0xFFE8F0F2)
val LightInversePrimary = Color(0xFF4CD9E8)

// --- Dark ---
val DarkPrimary = Color(0xFF5DD8E7)
val DarkOnPrimary = Color(0xFF00363D)
val DarkPrimaryContainer = Color(0xFF004F5B)
val DarkOnPrimaryContainer = Color(0xFFB9F1F5)
val DarkSecondary = Color(0xFFB6CBD3)
val DarkOnSecondary = Color(0xFF20343B)
val DarkSecondaryContainer = Color(0xFF354A52)
val DarkOnSecondaryContainer = Color(0xFFD2E7EE)
val DarkTertiary = Color(0xFFFFB68C)
val DarkOnTertiary = Color(0xFF512100)
val DarkTertiaryContainer = Color(0xFF6B320C)
val DarkOnTertiaryContainer = Color(0xFFFFDCC7)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF0E1417)
val DarkOnBackground = Color(0xFFDFE7EA)
val DarkSurface = Color(0xFF0B1114)
val DarkOnSurface = Color(0xFFDFE7EA)
val DarkSurfaceVariant = Color(0xFF3D494E)
val DarkOnSurfaceVariant = Color(0xFFBECAD0)
val DarkOutline = Color(0xFF87939A)
val DarkOutlineVariant = Color(0xFF3D494E)
val DarkInverseSurface = Color(0xFFDFE7EA)
val DarkInverseOnSurface = Color(0xFF0E1417)
val DarkInversePrimary = Color(0xFF0A7A8C)

// Profile accents (res/values/colors.xml profile_*)
val ProfileFreshwater = Color(0xFF2F9BB2)
val ProfileSaltwater = Color(0xFF3A6FC6)
val ProfilePond = Color(0xFF3E8E58)
